### ISSUE TITLE
APPDATA environment variable must exist when running on windows

### ISSUE THREAD

**Issue by ensslen** [pydata/pydata-google-auth#29]
The os.environ['APPDATA'] lookup in Cache.py line 29 always gets run, even if credentials are passed.  `%APPDATA%` is not guaranteed to be set, as it is not on the windows 2012R2 server service accounts that I have been attempting to use.

The resulting error message when APPDATA is not set is quite opaque.  Especially as the call which triggers the error, like my pandas.to_gbq() call, could have explicitly passed credentials.

This problem can be worked-around with 
`IF "%APPDATA%"=="" set APPDATA="PYDATA-GOOGLE-AUTH needs this to be set"`

**Comment by tswast** [comment]
Thanks for the report!

Can you expand more on what you mean by "even if credentials are passed"?

**Comment by tswast** [comment]
I believe this issue has been fixed in release 0.2.0.
