### ISSUE TITLE
ENH: Support authentication with service accounts

### ISSUE THREAD

**Issue by isidentical** [pydata/pydata-google-auth#39]
Service accounts use a different credentials class (`google.oauth2.service_account.Credentials`) and mostly used within a file that is expored from GCP console. It would be nice to have a `pydata_google_auth.load_service_account_credentials(path: os.PathLike) -> Credentials` method which does the initalization.

**Comment by tswast** [comment]
Can you help me understand this use case a little better? When would you like to use this function compared to calling `google-auth` directly or relying on the `GOOGLE_APPLICATION_CREDENTIALS` environment variable?

**Comment by isidentical** [comment]
The use case is having the equivalent of load_user_credentials, but for service auth. Example usage; https://github.com/isidentical/gdrivefs/blob/6993923963368726bf18112766e8d4d2574756f4/gdrivefs/core.py#L100-L110

**Comment by tswast** [comment]
OK. That makes some sense to me (one library to do all auth). When I have some time I'll take a closer look at your PR.

**Comment by isidentical** [comment]
Thanks!

**Comment by tswast** [comment]
It's actually been on my wishlist for a while to have a single function that loads any type of credentials file. The JSON includes a type field for this purpose https://github.com/pydata/pydata-google-auth/blob/master/pydata_google_auth/cache.py#L119

What if we add a generic `load_credentials_file` function instead?

**Comment by isidentical** [comment]
> What if we add a generic load_credentials_file function instead?

Wouldn't it make sense to have this separately, and maybe use the `load_credentials_file` as a separate function?

**Comment by tswast** [comment]
Yeah, that's fair. Doesn't hurt to have the explicit function.
