### ISSUE TITLE
use colab-specific auth if detected on colab

### ISSUE THREAD

**Issue by tswast** [pydata/pydata-google-auth#64]
Similar to #63, if we detect that we are on a colab environment, we can use the colab auth by default. Note: I think this should ignore the "local webserver" parameter, as colab uses a slightly different kind of flow.

**Comment by tswast** [comment]
I think internal colab is slightly different?

```
from colabtools import bigquery
from colabtools import auth

bigquery.magics.context.credentials = auth.get_user_oauth2_credentials(bigquery.SCOPES)
bigquery.magics.context.project = 'projectid'  # Replace with your project ID, eg "stunning-gauss-827"
```

**Comment by shobsi** [comment]
I tested the above steps (https://github.com/pydata/pydata-google-auth/issues/64#issuecomment-1463993845) on colab.corp.google.com. The authentication is successful but the client creation fails. Am I missing something?

![image](https://user-images.githubusercontent.com/10303222/227034600-561e6f91-1025-40fc-bd49-1b1a8a301762.png)

**Comment by shobsi** [comment]
This issue can be closed after https://github.com/pydata/pydata-google-auth/pull/68
