### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by patrick-mccaffrey** [pydata/pydata-google-auth#67]
Hey all,

I've been having some issues authenticating since the OOB deprecation and accompanying changes that have gone along with that. I'm trying to authenticate with either the `default()` or `get_user_credentials()` using `use_local_webserver=False` flag, and am unable to authenticate. I'm getting the following error:

> Error 400: redirect_uri_mismatch
> 
> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.
> 
> If you're the app developer, register the redirect URI in the Google Cloud Console.
> Request details: redirect_uri=https://pydata-google-auth.readthedocs.io/en/latest/oauth.html

If Google's error is to be believed, it looks as if the new redirect portal you've created needs to be registered on cloud console?

![image](https://user-images.githubusercontent.com/117293284/217630346-60adcdd4-355d-45af-8051-3cd491dd7eb3.png)

Curiously, I was able to authenticate by downgrading to version 1.5 and also downgrading my google-auth-oauthlib package to version 0.8. I've tried quite a few other troubleshooting approaches but I haven't gotten another workaround to stick.

Thanks so much for your work on this great package!

**Comment by kannanmunusamy** [comment]
Hello,

I am experiencing the same problem. Downgrading to 1.5.0 works, but only until May 1.

From Google Cloud, I received an email saying that older versions will no longer be able to authenticate on May 1, 2023.
To keep your authentication flows working, we should upgrade to a new version - pydata-google-auth: [v1.7.0] or newer.

I created an OAuth 2.0 Client ID (for redirect_uri=https://pydata-google-auth.readthedocs.io/en/latest/oauth.html)  in GCP, but it does not work.

Is it possible to fix this on priority? Thank you very much.

**Comment by kannanmunusamy** [comment]
Hey,

Thanks for fixing this.

Could you please help me understand this?

![image](https://user-images.githubusercontent.com/77729340/224750784-af6ba395-581f-4cd0-9a4b-10ee174826f8.png)

![image](https://user-images.githubusercontent.com/77729340/224750918-cf7cb24f-449c-4dce-bd1c-39c668ecb36f.png)

This will scare the users. Does it mean, PyData can access my google cloud data?
